### ISSUE TITLE
More than one issue

### ISSUE THREAD

**Issue by KILLERBOSS1024** [Distantz/Planet-Coaster-Mod-Loader#3]
Hello Distantz, i have reinstalled Planet Coaster recently and when i go into the game the mods dont show up so i went onto the PCModManager and i deleted the mods by clicking Uninstall all mods, then when i try to install Realism Overhaul V3 or anyother mod it says that they are already installed. I have tried to reinstall the Mod Manager and it does the same thing.

Error Number 1
![image](https://user-images.githubusercontent.com/81324529/112362273-2d877080-8ccc-11eb-9cbd-a761e66f4257.png)

Error Number 2
![image](https://user-images.githubusercontent.com/81324529/112362344-3e37e680-8ccc-11eb-82fc-71bd1a70db66.png)

Thanks
KILLERBOSS1024

**Comment by Neswo** [comment]
Me too
