### ISSUE TITLE
How to Reinstall the Mod Manager if you screwed up your directory settings.

### ISSUE THREAD

**Issue by Joey-Destroyah** [Distantz/Planet-Coaster-Mod-Loader#4]

**Comment by Joey-Destroyah** [comment]
Never mind. You have to go to %appdata%, then navigate to the PC manager folder and delete it, then relaunch the loader.
Sorry for wasting your time.

**Comment by Joey-Destroyah** [comment]
The instructions for this are ONLY for Windows

**Comment by isaacwhittle** [comment]
Could you run thru how you did this?

**Comment by Joey-Destroyah** [comment]
%appdata%, navagate to PCModManager, and delete the folder. Then reopen the application.

**Comment by isaacwhittle** [comment]
I can't seem to find %appdata%

**Comment by JovietUnion** [comment]
%appdata%, navagate to PCModManager, and delete the folder. Then reopen the application.

**Comment by Joey-Destroyah** [comment]
go to the address bar in file explorer, click it, then enter %appdata% then press enter. You'll be taken to a folder called Roaming. That's what you want.
